version: '3'

services:
  db:
    restart: always
    image: 'postgres'
    environment:
      - "POSTGRES_DB=UPciti"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

  web:
    build: .
    command: bash -c "python manage.py makemigrations api && python manage.py migrate api && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    depends_on:
      - db

  scraper:
    build:
      context: .
    depends_on:
    - db
    command: bash -c " python3 scrapping.py"
