# Generated by Django 3.1.1 on 2020-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('radio', models.TextField(blank=True, null=True)),
                ('mcc', models.BigIntegerField(blank=True, null=True)),
                ('net', models.BigIntegerField(blank=True, null=True)),
                ('area', models.BigIntegerField(blank=True, null=True)),
                ('cell', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('unit', models.BigIntegerField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('range', models.BigIntegerField(blank=True, null=True)),
                ('samples', models.BigIntegerField(blank=True, null=True)),
                ('changeable', models.BigIntegerField(blank=True, null=True)),
                ('created', models.BigIntegerField(blank=True, null=True)),
                ('updated', models.BigIntegerField(blank=True, null=True)),
                ('averagesignal', models.BigIntegerField(blank=True, db_column='averageSignal', null=True)),
            ],
            options={
                'db_table': 'Tower',

            },
        ),
    ]
